format = """
[░▒▓](#aed2a3)\
$os\
$username$hostname\
[](bg:#5f9046 fg:#aed2a3)\
$directory\
[](fg:#5f9046)
$git_branch\
$git_status\
[](fg:#426039 bg:#22301d)\
$nodejs\
$python\
[](fg:#22301d)\
\n$character"""

[username]
show_always = true
format = '[ $user](bg:#aed2a3 fg:#090c0c bold)'
disabled = false

[hostname]
ssh_only = false
format = '[@$hostname](bg:#aed2a3 fg:#090c0c bold)'

[directory]
style = "fg:#FFFFFF bg:#5f9046 bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_commit]
format = '[\($hash\)](yellow)[$tag](blue bold) '
tag_disabled = false
only_detached = false
tag_symbol = ' 󱩺 '

[git_branch]
format = '[ $symbol](fg:#eeebef bg:#426039)[$branch(:$remote_branch)](fg:#eeebef bg:#426039)'

[git_status]
format = '([ \[$all_status$ahead_behind\]](fg:#ce2029 bg:#426039 bold))'

[python]
format = '[ $symbol${pyenv_prefix}(${version}) (\($virtualenv\) )](fg:#FFFFFF bg:#22301d)'
symbol = '󰌠 '

[nodejs]
format = '[ $symbol$version ](fg:#FFFFFF bg:#22301d)'

[os]
format = "[$symbol](bg:#aed2a3 fg:#090c0c bold)"
disabled = false

[os.symbols]
Macos = "  "
Mint = " 󰌪 "
Fedora = "  "
